### ISSUE TITLE
Wrong Image Format for bootm command

### ISSUE THREAD

**Issue by swanduron** [clayface/U-boot-MX64-20190430_MX64#1]
Dear contributor, I have a question when I try to load initramfs image from USB. The initramfs has the correct SHA512 value but the screen still gives wrong feedback as below:

```
USB EHCI 1.00
scanning bus for devices... 2 USB Device(s) found
       scanning bus for storage devices... 1 Storage Device(s) found
reading openwrt-bcm53xx-generic-meraki_mx64-initramfs.bin

** Unable to read "openwrt-bcm53xx-generic-meraki_mx64-initramfs.bin" from usb 0:1 **
Wrong Image Format for bootm command
ERROR: can't get kernel image!
```

Could you give a finger on it?

**Comment by swanduron** [comment]
Here is all the output information.

```
U-Boot 2012.10 (May 05 2022 - 09:47:09)Meraki MX64 Boot Kernel Loader

DEV ID = 0xcf1e
PCIE CFG DEV ID = 0x8025
OTP offset(0x8): 0x78f01c01
OTP offset(0x9): 0xfe400818
OTP offset(0xa): 0xc01b0
OTP offset(0xb): 0x0
OTP offset(0xc): 0x4a00000
OTP offset(0xd): 0xffede250
OTP offset(0xe): 0x1135d17f
OTP offset(0xf): 0x4000
NSP25 32bit DDR
SKU ID = 0x0
DDR type: DDR3
MEMC 0 DDR speed = 800MHz
ddr_init2: Calling soc_ddr40_set_shmoo_dram_config
ddr_init2: Calling soc_ddr40_phy_calibrate
C01. Check Power Up Reset_Bar
C02. Config and Release PLL from reset
C03. Poll PLL Lock
C04. Calibrate ZQ (ddr40_phy_calib_zq)
C05. DDR PHY VTT On (Virtual VTT setup) DISABLE all Virtual VTT
C06. DDR40_PHY_DDR3_MISC
C07. VDL Calibration
C07.1
C07.2
C07.4
C07.4.1
C07.4.4
VDL calibration result: 0x30000003 (cal_steps = 0)
C07.4.5
C07.4.6
C07.5
C08. DDR40_PHY_DDR3_MISC : Start DDR40_PHY_RDLY_ODT....
C09. Start ddr40_phy_autoidle_on (MEM_SYS_PARAM_PHY_AUTO_IDLE) ....
C10. Wait for Phy Ready
Programming controller register
ddr_init2: Calling soc_ddr40_shmoo_ctl
Validate Shmoo parameters stored in flash ..... OK
Press Ctrl-C to run Shmoo ..... skipped
Restoring Shmoo parameters from flash ..... done
Running simple memory test ..... OK
DDR Tune Completed
DRAM:  2 GiB
WARNING: Caches not enabled
NAND:   Micron MT29F8G08ABACA, Found strap type 0x6 strap page 0x2
256 KiB blocks, 4 KiB pages, 27B OOB, 8-bit
NAND:   chipsize 1024 MiB
*** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
arm_clk=1200MHz, axi_clk=600MHz, apb_clk=300MHz, arm_periph_clk=600MHz
Enabling icache and dcache
Enabling l2cache
Registering eth
Broadcom BCM IPROC Ethernet driver 0.1
Using GMAC2 (0x18024000)
ERROR: could not get env ethaddr
et0: ethHw_chipAttach: Chip ID: 0xcf1e; phyaddr: 0x1e
bcm_robo_attach: devid: 0x10
Hit any key to stop autoboot:  0 
UBI: attaching mtd1 to ubi0
UBI: physical eraseblock size:   262144 bytes (256 KiB)
UBI: logical eraseblock size:    253952 bytes
UBI: smallest flash I/O unit:    4096
UBI: VID header offset:          4096 (aligned 4096)
UBI: data offset:                8192
UBI: attached mtd1 to ubi0
UBI: MTD device name:            "mtd=0"
UBI: MTD device size:            1015 MiB
UBI: number of good PEBs:        4060
UBI: number of bad PEBs:         0
UBI: max. allowed volumes:       128
UBI: wear-leveling threshold:    4096
UBI: number of internal volumes: 1
UBI: number of user volumes:     5
UBI: available PEBs:             1647
UBI: total number of reserved PEBs: 2413
UBI: number of PEBs reserved for bad PEB handling: 40
UBI: max/mean erase counter: 359/345
Read 0 bytes from volume kernel to 90000000
Volume kernel not found!
(Re)start USB...
USB:   Before reset, USB clk enable register is: 000002dd
Before reset, USB clk enable register is: 000002dd
usb2_reset_state is: 00000000
Register 1212 NbrPorts 2
USB EHCI 1.00
scanning bus for devices... 2 USB Device(s) found
       scanning bus for storage devices... 1 Storage Device(s) found
reading openwrt-bcm53xx-generic-meraki_mx64-initramfs.bin

** Unable to read "openwrt-bcm53xx-generic-meraki_mx64-initramfs.bin" from usb 0:1 **
Wrong Image Format for bootm command
ERROR: can't get kernel image!
```

**Comment by clayface** [comment]
> ** Unable to read "openwrt-bcm53xx-generic-meraki_mx64-initramfs.bin" from usb 0:1 **

Hello, this message indicates the file can't be read. Can you check the USB disk is formatted correctly? It should be DOS partition scheme with a primary partition formatted as FAT32.

Edit: Also verify you have the correct filename. The image it is looking for is that from the updated [PR](https://github.com/openwrt/openwrt/pull/3996) that uses a FIT image.

**Comment by swanduron** [comment]
Very thanks for your quick reply! It's amazing!

In addition to this question, I'm also confused by another problem. It's that the USB system is not stable but I can't be sure it's my hardware issue or other reasons. I have 11 USB disks, I will try them one by one and hope one of them can work correctly :P 

```
u-boot> usb reset
(Re)start USB...
USB:   Before reset, USB clk enable register is: 000002dd
Before reset, USB clk enable register is: 000002dd
usb2_reset_state is: 00000000
EHCI fail to reset
Error, couldn't init Lowlevel part
u-boot> usb stop
stopping USB..
u-boot> usb start
(Re)start USB...
USB:   Before reset, USB clk enable register is: 000002dd
Before reset, USB clk enable register is: 000002dd
usb2_reset_state is: 00000000
EHCI fail to reset
Error, couldn't init Lowlevel part
```

**Comment by swanduron** [comment]
> 

I fully followed your guide. My device is 0x3F05 with mtd lock.

**Comment by swanduron** [comment]
> > ** Unable to read "openwrt-bcm53xx-generic-meraki_mx64-initramfs.bin" from usb 0:1 **
> 
> Hello, this message indicates the file can't be read. Can you check the USB disk is formatted correctly? It should be DOS partition scheme with a primary partition formatted as FAT32.
> 
> Edit: Also verify you have the correct filename. The image it is looking for is that from the updated [PR](https://github.com/openwrt/openwrt/pull/3996) that uses a FIT image.

I fully followed your guide. My device is 0x3F05 with mtd lock.

**Comment by clayface** [comment]
> It's that the USB system is not stable but I can't be sure it's my hardware issue or other reasons. I have 11 USB disks, I will try them one by one and hope one of them can work correctly :P

I suggest you reset the device each time and see if that makes a difference. Try running `reset`, stopping autoboot, then do `mx64init ; usb start`. mx64init is needed to bring up the USB phy.

**Comment by swanduron** [comment]
> > It's that the USB system is not stable but I can't be sure it's my hardware issue or other reasons. I have 11 USB disks, I will try them one by one and hope one of them can work correctly :P
> 
> I suggest you reset the device each time and see if that makes a difference. Try running `reset`, stopping autoboot, then do `mx64init ; usb start`. mx64init is needed to bring up the USB phy.

I understand something occurs. The system tries to find the initramfs named `openwrt-bcm53xx-generic-meraki_mx64-initramfs.bin` but in this repo the file name is `openwrt-bcm5862x-generic-meraki_mx64-initramfs-kernel.bin`.

But the same result, the renamed image still didn't work.

```
scanning bus for devices... 2 USB Device(s) found
       scanning bus for storage devices... 1 Storage Device(s) found
reading openwrt-bcm53xx-generic-meraki_mx64-initramfs.bin
....................................
5242912 bytes read
Wrong Image Format for bootm command
ERROR: can't get kernel image!
```

Right now I want to compile a new firmware of openwrt, but I can't find the corresponding target system and target profile. Could you let me how to get the newer MX64 firmware? Or it shares profile with MR32?

**Comment by clayface** [comment]
> I understand something occurs. The system tries to find the initramfs named `openwrt-bcm53xx-generic-meraki_mx64-initramfs.bin` but in this repo the file name is `openwrt-bcm5862x-generic-meraki_mx64-initramfs-kernel.bin`.

That's correct. Don't use this image because it is only for users who installed the previous bootloader I provided, which used the bcm5862x platform. The old u-boot also used the `bootbk` function (which is why you receive an error) with the bootkernel1 partition, but this partition is only 3MiB which is too small. The new u-boot uses bootm and UBI support so it can work with larger kernels.

To get it working you need to compile your own image(with initramfs enabled) from the PR. I don't have an image I can provide right now unfortunately but maybe later I can compile one. If accepted into OpenWrt they will provide this image in the future.

**Comment by clayface** [comment]
I found some images - these are just to get the device up and running. I still suggest you compile your own with the features you need of course.

initramfs:
https://app.box.com/s/5bxb65xuo5y5p7c2jwuskdcq59wh8932
sysupgrade:
https://app.box.com/s/c1ugjjkjdk57cvotpxd962nvezut5htp

**Comment by swanduron** [comment]
> I found some images - these are just to get the device up and running. I still suggest you compile your own with the features you need of course.
> 
> initramfs: https://app.box.com/s/5bxb65xuo5y5p7c2jwuskdcq59wh8932 sysupgrade: https://app.box.com/s/c1ugjjkjdk57cvotpxd962nvezut5htp

It works! All functions seem OK and have no explicit defect in a glimpse. 

It seems too long to bother you on a nice day (week?). Let's close this ticket. I will follow this platform stable (we have a lot of cheap MX64....).  I don't expect you to do more, but thank you very much.

**Comment by clayface** [comment]
No problem.

> we have a lot of cheap MX64

Can you find an MX65? It is a much more interesting device.

**Comment by swanduron** [comment]
> No problem.
> 
> > we have a lot of cheap MX64
> 
> Can you find an MX65? It is a much more interesting device.

No. Just have MX64 and MX67. MX65 looks easy to operate, not as complicated as MX64 ToT

**Comment by geludanis** [comment]
Hello,

I know this is an old post but I'm still trying to follow clayface's step by step guide, at the moment I'm stuck on uboot and I can't figure out what I am doing wrong. Any advice will be more than helpful. Thanks in advance. Below is printview at the moment.

u-boot> printenv
baudrate=115200
bootargs=console=ttyS0,115200n8 earlyprintk
bootcmd=run soc_dtscheck; mx64init; run ubi_checkboot; run usb_checkboot; run me                             raki_checkboot
bootdelay=3
bootfile=uImage
config_dts=config@2
disable_ubi_boot=0
enable_meraki_boot=0
enable_usb_boot=1
initramfs_filename=openwrt-bcm53xx-generic-meraki_mx64-initramfs.bin
initramfs_filename_a0=openwrt-bcm53xx-generic-meraki_mx64_a0-initramfs.bin
ipaddr=192.168.0.1
loadaddr=0x90000000
meraki_bootkernel1=nand read 0x60008000 0x100000 0x300000; bootbk 0x60008000 boo                             tkernel1
meraki_bootkernel2=nand read 0x60008000 0x500000 0x300000; bootbk 0x60008000 boo                             tkernel2
meraki_checkboot=if test $enable_meraki_boot = 1; then run meraki_bootkernel2; r                             un meraki_bootkernel1; fi
mtddevname=ubi
mtddevnum=0
mtdids=nand0=nand_iproc.0
mtdparts=mtdparts=nand_iproc.0:0x3F700000@0x800000(ubi)
partition=nand0,0
soc_dtscheck=if test -n config_dts; then getsocrev; if test $? = 1 ; then setenv                              config_dts config@4; else setenv config_dts config@2; fi; fi
stderr=serial
stdin=serial
stdout=serial
ubi_boot=ubi part ubi && ubi read ${loadaddr} kernel && bootm ${loadaddr}#${conf                             ig_dts}
ubi_checkboot=if test $disable_ubi_boot != 1; then run ubi_boot ; fi
usb_checkboot=if test $enable_usb_boot = 1; then usbload; fi

Environment size: 1313/262140 bytes

Trying to reset and stoping autoboot I get this:

(Re)start USB...
USB:   Before reset, USB clk enable register is: 000000cd
Before reset, USB clk enable register is: 000000cd
usb2_reset_state is: 00000000
EHCI fail to reset
Error, couldn't init Lowlevel part
** Bad device usb 0 **
Wrong Image Format for bootm command
ERROR: can't get kernel image!
